{
 "title": "Docker Logs",
 "description": "Easily view the last x minutes of logs from ETH Docker (https://eth-docker.net/)  containers via Loki data source",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Infra Agent Health",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_source=\"docker\", container_name=\"cure-alloy\"}"
    }
   ]
  },
  {
   "title": "Spring Boot Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_source=\"spring_boot\"}"
    }
   ]
  },
  {
   "title": "Nginx Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_source=\"docker\", compose_service=\"nginx\"}"
    }
   ]
  },
  {
   "title": "DB Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{log_source=\"docker\", compose_service=\"mongodb\"}"
    },
    {
     "direction": "backward",
     "expr": "{log_source=\"docker\", compose_service=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Cache/Kafka Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{log_source=\"docker\", compose_service=\"redis\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{log_source=\"docker\", compose_service=\"redpanda\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}